Proc ep rtoi func
jmfrancklab/proc_scripts pull request #126
Opened 2024-09-30 22:20 UTC by wfkincaid

2024-09-30 22:26 UTC, wfkincaid commented
I think I did this right, it should be the use_rough_table PR + the new file `proc_Ep.py`

2024-10-01 00:55 UTC, jmfranck commented on examples/proc_Ep.py
> -    fl.show()
the with block handles show.

2024-10-02 23:59 UTC, wfkincaid commented
I added a lot to proc_Ep trying to incorp in the power log stuff but it further made me feel that the power log should be handled by a function. One reason for this is that some of the info from the power log will be needed for fitting and plotting along the power axis with proc_FIR

2024-10-06 00:10 UTC, jmfranck requested changes

2024-10-06 00:10 UTC, jmfranck commented on examples/proc_Ep.py
> -    s = prscr.convert_to_power(thisfile, exptype, s, fl=fl)
I just moved this to the end so that we could see the older plot (which I thought was kind of nice) as well as the final plot.

2024-10-06 00:10 UTC, jmfranck commented on examples/proc_Ep.py
> +    # (delete when read) just note that I moved this to the end
yes, just delete.

2024-10-06 00:10 UTC, jmfranck commented on pyspecProcScripts/convert_to_power.py
> +        This is an nddata whose "indirect"
I added to the docstring a bit

2024-10-06 00:10 UTC, jmfranck commented on pyspecProcScripts/convert_to_power.py
> +        re.escape(filename), exp_type=exp_type, unique=True
just using consistent naming

2024-10-06 00:10 UTC, jmfranck commented on pyspecProcScripts/convert_to_power.py
> +    ), str(s["indirect"].dtype.names)
just checking that the data is in the expected format

2024-10-06 00:10 UTC, jmfranck commented on pyspecProcScripts/convert_to_power.py
> +    log_vs_time = prscr.dBm2power(log_vs_time + 20)
I posted a message about this in the processing scripts channel

2024-10-06 00:10 UTC, jmfranck commented on pyspecProcScripts/convert_to_power.py
> +    log_vs_time = prscr.dBm2power(log_vs_time + 20)
as I see it, this is the only thing that needs to be taken care of before closing the PR.

2024-10-06 00:10 UTC, jmfranck commented on pyspecProcScripts/convert_to_power.py
> +    ).set_units("indirect", "W")
the `s['indirect']` is a numpy array.  It has a `data` attribute, but I think that's not what you're going for here. 

btw, what I'm doing in the setaxis call is the same as `s['indirect'] = mean_power_vs_time.data` I just like stringing the calls together.

2024-10-08 14:32 UTC, merged